### ISSUE TITLE
Who calls run() in CaptureModule.cpp

### ISSUE THREAD

**Issue by elomazov** [obraun-sl/qtZEDViewer#1]
You have this code in CaptureModule.cpp:

```
void CaptureModule::startCapture()
{
    if (opened_ && run_)
        start();
}

void CaptureModule::run() {
    sl::RuntimeParameters grab_params;
    grab_params.enable_depth = true;
    while (run_) {
        cuCtxSetCurrent(context);
        sl::ERROR_CODE err_ = this->zed_.grab(grab_params);
        if (err_ == sl::ERROR_COD
```

CaptureModule::startCapture() calls start() which opens a thread
CaptureModule::run() isn't called anywhere in the code

**Is start() supposed to actually say run()? I'm struggling to understand the logic/use of run(). Please advise.**

**Comment by obraun-sl** [comment]
As part of QThread, start() function will call run() in the event loop.
See Doc here : https://doc.qt.io/qt-5/qthread.html#start

**Comment by elomazov** [comment]
Thank you so much! I ended up finding this document right after I posted the question.
